# User config
author: "Sasha & Flower"
tagline: "Sasha Flower"
description: "In 2018, I started taking flower lessons to escape from my everyday life. I try to record what I learned in class. Enjoy flowers<i class='sf-bouquet'></i>"
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "runningsasha@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/sasha"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed