# User config
author: "Sasha & Flower Diary"
tagline: "Sasha Flower"
description: "Live better with flowers <i class='sf-bouquet'></i>"
email: "runningsasha@gmail.com"
linkedin: "https://www.linkedin.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed