# User config
author: "Sasha & Flower Diary"
tagline: "Sasha Flower"
description: "2018년 회사와 집을 반복하며 평온한 하루하루를 보내던 중. 일상생활에 변화를 주고 싶어서 꽃 수업을 듣기 시작했습니다. 수업에서 배운 것들을 기록해보려고 합니다 <i class='sf-bouquet'></i>"
email: "runningsasha@gmail.com"
linkedin: "https://www.linkedin.com/"
github: "https://github.com/"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed